name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of Gryt is affected?
      options:
        - Client (Desktop / Electron)
        - Client (Web / Docker)
        - Server
        - SFU
        - Docs
        - Other
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear description of the bug.
      placeholder: Describe the issue...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Exact steps so we can reproduce the issue.
      placeholder: |
        1. Go to ...
        2. Click on ...
        3. See error ...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What did you expect to happen instead?
      placeholder: I expected ...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Fill in everything that applies.
      value: |
        - **OS:** 
        - **Gryt version:** 
        - **Deployment:** [Docker / source / gryt.chat]
        - **Self-hosted:** [yes / no]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / error output
      description: Paste any relevant log output or error messages.
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the problem.
